"""empty message

Revision ID: eadc67878ca5
Revises: 
Create Date: 2020-12-16 01:00:20.670118

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.password

# revision identifiers, used by Alembic.
revision = 'eadc67878ca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('word',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pronunciation', sa.String(), nullable=True),
    sa.Column('definition_count', sa.Integer(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('similar_to', sa.String(), nullable=True),
    sa.Column('type_of', sa.String(), nullable=True),
    sa.Column('also', sa.String(), nullable=True),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('attribute', sa.String(), nullable=True),
    sa.Column('antonyms', sa.String(), nullable=True),
    sa.Column('synonyms', sa.String(), nullable=True),
    sa.Column('has_types', sa.String(), nullable=True),
    sa.Column('examples', sa.String(), nullable=True),
    sa.Column('word_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_definition_word_id'), 'definition', ['word_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'word_id', 'year', 'month', 'day')
    )
    op.create_table('vocab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_user_id'), 'vocab', ['user_id'], unique=False)
    op.create_table('vocab_word',
    sa.Column('word_id', sa.String(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('view', sa.Integer(), nullable=False),
    sa.Column('practice_point', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'vocab_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_word')
    op.drop_index(op.f('ix_vocab_user_id'), table_name='vocab')
    op.drop_table('vocab')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_definition_word_id'), table_name='definition')
    op.drop_table('definition')
    op.drop_table('word')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
